version: '3.6'

services:
  db:
    image: mvertes/alpine-mongo
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_ROOT_PASSWORD
      - MONGO_DATABASE
      - MONGO_USER
      - MONGO_PASSWORD
      - TZ=${MONGO_TZ}
    volumes:
      - ./mongodb-data:/var/lib/mongo/data
    expose:
      - ${MONGO_PORT}
      
