version: '3.6'

services:
  db:
    image: mvertes/alpine-mongo
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_ROOT_PASSWORD
      - MONGO_DATABASE
      - MONGO_USER
      - MONGO_PASSWORD
      - TZ=${MONGO_TZ}
    volumes:
      - mongo_data:/var/lib/mongo/data
    expose:
      - ${MONGO_PORT}

  client:
    image: mongoclient/mongoclient:2.2.0
    restart: always
    ports:
      - "${MONGO_CLIENT_PORT}:3000"

volumes:
  mongo_data:
